//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BusinessPlanGallery
    {
        public int GalleryID { get; set; }
        public Nullable<int> BusinessPlan_id { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public string ImageName { get; set; }
        public string Title { get; set; }
    
        public virtual Tbl_BussinessPlans Tbl_BussinessPlans { get; set; }
    }
}
