//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Settings
    {
        public int SettingID { get; set; }
        public string SiteTItle { get; set; }
        public string SiteDescription { get; set; }
        public string AboutUs { get; set; }
        public string Slogen { get; set; }
        public string SiteLogo { get; set; }
        public string SiteRules { get; set; }
        public string PartnershipAgreements { get; set; }
        public string RiskWarningStatement { get; set; }
        public string InstagramUrl { get; set; }
        public string LinkedinUrl { get; set; }
        public string WhatsappUrl { get; set; }
        public string AparatUrl { get; set; }
        public string Location { get; set; }
        public string Permits { get; set; }
        public string ContactUs { get; set; }
        public string InvestmentProcess { get; set; }
        public string CapitalApplicationProcess { get; set; }
        public string CampaignProcess { get; set; }
        public string SiteTermsConditions { get; set; }
        public string Privacy { get; set; }
        public string RiskAlertStatement { get; set; }
        public string RiskAlertStatementFullText { get; set; }
        public string IntroductionCompanyTitle { get; set; }
        public string IntroductionCompanyDescription { get; set; }
        public string IntroductionCompanyFullText { get; set; }
        public string InvestmentRole { get; set; }
    }
}
