//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SejamTempNationalCode
    {
        public string ID { get; set; }
        public string NationalCode { get; set; }
        public Nullable<System.DateTime> CreteDate { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> User_id { get; set; }
        public bool IsActive { get; set; }
    }
}
