//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SajamToken
    {
        public int ID { get; set; }
        public string Token { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string TTL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
