//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BussinessPlan_BussinessTypes
    {
        public int BussinessTypeID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string BussinessTypeTItle { get; set; }
    }
}
