//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MenuPage
    {
        public int MenuPageID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Url { get; set; }
        public Nullable<int> Page_id { get; set; }
        public Nullable<int> MenuType_id { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual Tbl_MenuType Tbl_MenuType { get; set; }
    }
}
