//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Wallet
    {
        public int ID { get; set; }
        public int User_id { get; set; }
        public int Type_id { get; set; }
        public long Amount { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
        public virtual Tbl_WalletType Tbl_WalletType { get; set; }
    }
}
