//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Tickets()
        {
            this.Tbl_Tickets1 = new HashSet<Tbl_Tickets>();
        }
    
        public int TicketID { get; set; }
        public Nullable<int> Parent_id { get; set; }
        public bool IsDelete { get; set; }
        public bool IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public bool IsUserChecked { get; set; }
        public bool IsAdminChecked { get; set; }
        public Nullable<System.DateTime> UserCheckedDateTime { get; set; }
        public Nullable<System.DateTime> AdminCheckedDateTime { get; set; }
        public string AttachFileName { get; set; }
        public Nullable<int> AdminChecked_id { get; set; }
        public Nullable<int> UserCreate_id { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public Nullable<int> DeleteUser_id { get; set; }
        public Nullable<System.DateTime> EditDateTime { get; set; }
        public Nullable<int> EditUser_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Tickets> Tbl_Tickets1 { get; set; }
        public virtual Tbl_Tickets Tbl_Tickets2 { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
        public virtual Tbl_Users Tbl_Users1 { get; set; }
        public virtual Tbl_Users Tbl_Users2 { get; set; }
        public virtual Tbl_Users Tbl_Users3 { get; set; }
        public virtual Tbl_Users Tbl_Users4 { get; set; }
    }
}
