//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_WalletWithdrawalRequest
    {
        public long ID { get; set; }
        public Nullable<int> User_Id { get; set; }
        public long Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<int> WithdrawalStatus { get; set; }
        public Nullable<System.DateTime> StatusEditDate { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
        public virtual Tbl_WalletWithdrawalStatus Tbl_WalletWithdrawalStatus { get; set; }
    }
}
