//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PaymentOnlineDetils
    {
        public string PaymentDetilsID { get; set; }
        public bool IsDelete { get; set; }
        public bool IsFinally { get; set; }
        public Nullable<int> Payment_id { get; set; }
        public string ShaparakMessageGetToken { get; set; }
        public string ShaparakToken { get; set; }
        public string TransactionReferenceID { get; set; }
        public string ShaparakCheckTransactionResult { get; set; }
        public string ShaparakVerifyPayment { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> FinallyDate { get; set; }
        public Nullable<int> Dargah_id { get; set; }
    
        public virtual Tbl_BusinessPlanPayment Tbl_BusinessPlanPayment { get; set; }
        public virtual Tbl_Dargah Tbl_Dargah { get; set; }
    }
}
