//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Affiliate
    {
        public int ID { get; set; }
        public Nullable<int> Token_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual Tbl_ApiToken Tbl_ApiToken { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
