//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_RequestFinancing
    {
        public int ID { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> Status_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string DescriptionAdmin { get; set; }
        public string DescriptionAdminHidden { get; set; }
    
        public virtual Tbl_RequestFinancingStatus Tbl_RequestFinancingStatus { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
