//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DepositToInvestorsDetails
    {
        public int DepositDetailID { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Deposit_id { get; set; }
        public Nullable<int> InvestorUser_id { get; set; }
        public Nullable<long> DepositAmount { get; set; }
        public Nullable<int> CreateUser_id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DeleteUser_id { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Tbl_DepositToInvestors Tbl_DepositToInvestors { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
        public virtual Tbl_Users Tbl_Users1 { get; set; }
        public virtual Tbl_Users Tbl_Users2 { get; set; }
    }
}
