//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CommentPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_CommentPlan()
        {
            this.Tbl_CommentPlan1 = new HashSet<Tbl_CommentPlan>();
        }
    
        public int CommentID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Parent_id { get; set; }
        public Nullable<int> BusinessPlan_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CommentText { get; set; }
    
        public virtual Tbl_BussinessPlans Tbl_BussinessPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CommentPlan> Tbl_CommentPlan1 { get; set; }
        public virtual Tbl_CommentPlan Tbl_CommentPlan2 { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
