//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserProfiles
    {
        public int ProfileID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> User_id { get; set; }
        public string MobileNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImageName { get; set; }
        public string Bio { get; set; }
        public string NationalCode { get; set; }
        public string FatherName { get; set; }
        public string ProfileNationalId { get; set; }
        public string SejamCode { get; set; }
        public string AccountNumber { get; set; }
        public string AccountSheba { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string PlaceOfIssue { get; set; }
        public string PlaceOfBirth { get; set; }
        public string SignitureFile { get; set; }
        public string strSejamResponse { get; set; }
        public string strBirthDate { get; set; }
    
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
