//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DepositToInvestorsDetails
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string AccountSheba { get; set; }
        public Nullable<long> DepositAmount { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Plan_id { get; set; }
        public Nullable<int> Deposit_id { get; set; }
        public string NationalId { get; set; }
        public string NationalCode { get; set; }
    }
}
